namespace LiveSplit.OriWotW {
    public enum AbilityType : byte {
        None = 255,
        Bash = 0,
        ChargeFlame = 2,
        WallJump,
        Stomp,
        DoubleJump,
        ChargeJump = 8,
        Magnet = 10,
        UltraMagnet,
        Climb,
        Glide = 14,
        SpiritFlame,
        RapidFlame = 17,
        SplitFlameUpgrade,
        SoulEfficiency = 22,
        WaterBreath,
        ChargeFlameBlast = 27,
        ChargeFlameBurn,
        DoubleJumpUpgrade,
        BashBuff,
        UltraDefense,
        HealthEfficiency,
        Sense,
        UltraStomp,
        SparkFlame = 36,
        QuickFlame,
        MapMarkers,
        EnergyEfficiency,
        HealthMarkers,
        EnergyMarkers,
        AbilityMarkers,
        Rekindle,
        Regroup,
        ChargeFlameEfficiency,
        UltraSoulFlame,
        SoulFlameEfficiency,
        CinderFlame,
        UltraSplitFlame,
        Dash,
        Grenade,
        GrenadeUpgrade,
        ChargeDash,
        AirDash,
        GrenadeEfficiency,
        Bounce,
        SpiritLeash,
        SpiritSlash,
        HeavySpiritSlash,
        FireburstSpell,
        FirewhirlSpell,
        GlowSpell,
        LockOnSpell,
        TimeWarpSpell,
        ShieldSpell,
        EnergyWallSpell,
        InvisibilitySpell,
        TrapSpell,
        WarpSpell,
        LightSpell,
        MindControlSpell,
        MirageSpell,
        StickyMineSpell,
        SpiritSpearSpell,
        LightSpearSpell,
        LifeAbsorbSpell,
        MeditateSpell,
        ChargeShotSpell,
        SpiritShardsSpell,
        SpiritSentrySpell,
        PowerslideSpell,
        CounterstrikeSpell,
        EarthShatterSpell,
        JumpShotSpell,
        RoundupLeashSpell,
        BurrowSpell,
        PowerOfFriendshipSpell,
        LightningSpell,
        SpiritFlareSpell,
        EntanglingRootsSpell,
        MarkOfTheWildsSpell,
        HomingMissileSpell,
        SpiritCrescentSpell,
        MineSpell,
        Pinned,
        Leached,
        Bow,
        Hammer,
        Torch,
        Sword,
        Digging,
        DashNew,
        Launch,
        WaterDash,
        TeleportSpell,
        ChakramSpell,
        Drill,
        GoldenSein,
        BowCharge,
        Swordstaff,
        Chainsword,
        SpiritMagnet,
        SwordCharge,
        HammerCharge,
        Blaze,
        TurretSpell,
        Regenerate,
        FeatherFlap,
        WeaponCharge,
        DamageUpgradeA,
        DamageUpgradeB
    }
}