namespace LiveSplit.OriWotW {
    public enum EquipmentType {
        None,
        Weapon_Hammer = 1000,
        Weapon_Bow,
        Weapon_Sword,
        Weapon_Torch,
        Weapon_Swordstaff,
        Weapon_Chainsword,
        Spell_Shot = 2000,
        Spell_HomingMissiles,
        Spell_Wave,
        Spell_Whirl,
        Spell_Glow,
        Spell_LockOn,
        Spell_Shield,
        Spell_Invisibility,
        Spell_LifeAbsorb,
        Spell_Shards,
        Spell_StickyMine,
        Spell_Sentry,
        Spell_Spear,
        Spell_Meditate,
        Spell_Teleport,
        Spell_Chakram,
        Spell_Blaze,
        Spell_Turret,
        Spell_GoldenSein,
        Spell_ChargeJump,
        Ability_Bash = 3000,
        Ability_Leash,
        Ability_Digging,
        Ability_Drill,
        Ability_DoubleJump,
        Ability_FeatherFlap,
        AutoAbility_Dash = 4000,
        AutoAbility_Bounce,
        AutoAbility_Glide,
        AutoAbility_ChargeJump,
        AutoAbility_WaterDash,
        AutoAbility_Climb,
        AutoAbility_WeaponCharge,
        AutoAbility_DamageUpgradeA,
        AutoAbility_DamageUpgradeB,
        AutoAbility_WaterBreath
    }
}