namespace LiveSplit.OriWotW {
    public enum WorldMapIconType {
        Keystone,
        Mapstone,
        BreakableWall,
        BreakableWallBroken,
        StompableFloor,
        StompableFloorBroken,
        EnergyGateTwo,
        EnergyGateOpen,
        KeystoneDoorFour,
        KeystoneDoorOpen,
        AbilityPedestal,
        HealthUpgrade,
        EnergyUpgrade,
        SavePedestal,
        AbilityPoint,
        KeystoneDoorTwo,
        Invisible,
        Experience,
        MapstonePickup,
        EnergyGateTwelve,
        EnergyGateTen,
        EnergyGateEight,
        EnergyGateSix,
        EnergyGateFour,
        SpiritShard,
        NPC,
        QuestItem,
        ShardSlotUpgrade,
        Teleporter,
        Ore,
        HealthFragment = 33,
        EnergyFragment,
        Seed,
        QuestStart = 30,
        QuestEnd,
        RaceStart,
        RaceEnd = 36,
        Eyestone,
        WatermillDoor = 40,
        TempleDoor,
        SmallDoor,
        Shrine,
        Loremaster = 50,
        Weaponmaster,
        Gardener,
        Mapmaker,
        Shardtrader,
        Wanderer,
        Treekeeper,
        Builder,
        Kwolok,
        Statistician,
        CreepHeart,
        Miner,
        Spiderling,
        Moki,
        MokiBrave,
        MokiAdventurer,
        MokiArtist,
        MokiDarkness,
        MokiFashionable,
        MokiFisherman,
        MokiFrozen,
        MokiKwolokAmulet,
        MokiSpyglass,
        Ku,
        IceFisher,
        Siira
    }
}